### ISSUE TITLE
TypeError: tar.Extract is not a function

### ISSUE THREAD

**Issue by a1209910** [Kitware/arctic-viewer#24]
Hi,
I installed ArcticViewer and can start the usage menu.

When I try to download sample data I get the following:

_ArcticViewer --download-sample-data

 | Available datasets for download (path: /Users/magdalenaschwarzl/Documents/uni/coursesUtahGIT/research/paraviewWeb)
 |   (1)  40.0 MB  -  diskout-composite
 |   (2)  94.2 MB  -  ensemble
 |   (3)  13.7 MB  -  head_ct_3_features
 |   (4)  13.1 MB  -  head_ct_4_features
 |   (5)  50.8 MB  -  hydra-image-fluid-velocity
 |   (6) 162.3 MB  -  mpas-composite-earth
 |   (7)  37.5 MB  -  mpas-flat-earth-prober
 |   (8) 552.5 MB  -  mpas-hd-500-7t
 | 
 | Press Enter to quit or the dataset number to download: 1
 | Press Enter to quit or the dataset number to download: 5
 | Press Enter to quit or the dataset number to download: 8
 | Press Enter to quit or the dataset number to download: 
 |
 | => You will be able to try ArcticViewer with these commands:
 |
/usr/local/lib/node_modules/arctic-viewer/node_modules/tarball-extract/tarball.js:11
    .pipe(tar.Extract({ path: destination}))
              ^

TypeError: tar.Extract is not a function
    at extractTarball (/usr/local/lib/node_modules/arctic-viewer/node_modules/tarball-extract/tarball.js:11:15)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/arctic-viewer/node_modules/tarball-extract/tarball.js:30:5)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/arctic-viewer/node_modules/wget/lib/wget.js:51:28)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)_

**Comment by jourdain** [comment]
It seems that 5 and 8 are corrupted files. We'll investigate once back to the office.

**Comment by leopessanha74** [comment]
Hi! 
I believe its not about corrupted files.

I spent a day trying to fix this error and I could not solve it because I am begginer when it comes to node/npm/linux systems but I have come to a conclusion. 

ArcticViewer has its own node_modules in /usr/local/lib/node-modules/arctic-viewer/node-modules

The thing is the 'tarball-extract' module uses 'tar' module

**The tar module version in the ArctictViewer is 3.1.5 and the function "tar.Extract" has been modified to "tar.x" in the 3.1.5 version**

The solution:

**Rollback tar module version in the node-modules of ArcticViewer to 2.2.1(last one with "tar.Extract").**

I don't know how to do that.

In my machine '/usr/local/lib/node_modules/arctic-viewer/node_modules/tar' has version 3.1.5

but '/home/user/node_modules/tar' has version 2.2.1

**Copying the content fo version 2.2.1 to the '/usr/local/lib/node_modules/arctic-viewer/node_modules/tar' does not work.**

Someone help me!

Thanks in advance!

**Comment by scottwittenburg** [comment]
It seems if we just update our dependency on `tarball-extract` to `0.0.5`, we could be all set, as they have rolled back their own dependency on the `tar` package for the very reasons you discovered on your own:

https://github.com/matsieftw/tarball-extract/commit/970ab467e1726eaef21ba3c2f5fb42a36497cf91

I have not run into this problem yet, or verified the issue, but fairly soon we may have a chance to look into it.

**Comment by scottwittenburg** [comment]
Note that if you're in a hurry to get it working, you could try updating that dependency locally, removing your `node_modules` folder, and running `npm install`.  If you do that, let us know if it solves the problem for you.

**Comment by leopessanha74** [comment]
I don't know how to do that.

I mean, I can delete my home/user/node_modules folder and do a npm install, but I don't believe it would change much, since my local  tar version is 2.2.1 and tarball-extract is 0.0.6 

What I don't know what to do and believe it would help is how to change the tar(3.1.5) and tarball-extract(0.0.3) in the .../ArcticViewer/node_modules folder. 

I am not used to Linux, and I am not used to node yet so things like the difference between '/usr/local/opt' -> '/opt' and '/home/node-modules' -> '/usr/local/lib/node_modules/arctic-viewer/node_modules/' when installing/using a software are still a obstacle for me.

**Comment by scottwittenburg** [comment]
If you got your hands on ArcticViewer by doing `npm install -g arctic-viewer` (perfectly reasonable, as that's what the README says to do), then it will be harder for you to test changing the dependency on `tarball-extract`.  If you cloned the `arctic-viewer` repository on github, then it would be easy to try out what I suggested.  We may have a chance to address this issue ourselves soon, but not immediately.

**Comment by leopessanha74** [comment]
I did 'npm install -g arctic-viewer'.
I can wait.

Thank you Scott.

**Comment by nvuaille** [comment]
I had same problem here, using local clone of ArcticViewer.
Using tarball-extract  0.0.5, as suggested by @scottwittenburg works fine for me.
